apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: profile-service
build:
  artifacts:
    - image: casha-profile-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
        - BP_JVM_VERSION=17.*
#  local:
#    push: false
manifests:
  rawYaml:
    - k8s/deployment.yml
    - k8s/service.yml
