server:
  context-path: /profile-service
  port: 8080

spring:
  application:
    name: profile-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DATABASE:cs_profile}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  liquibase:
    change-log: db-script/profile_schema.sql

  security:
    oauth2:
      resourceserver.jwt.jwk-set-uri: ${OAUTH2_CLIENT_ISSUER_URI:http://localhost:9000}/oauth2/jwks
